In [4]:
import numpy as np
import time

In [11]:
# compare executeion time of python list and numpy array
size = 1_000_000

# for python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time: {end - start} seconds")

# for numpy array
np_array = np.array(py_list)
start = time.time()
sq = np_array ** 2
end = time.time()
print(f"NumPy array time: {end - start} seconds")

Python list time: 0.13814234733581543 seconds
NumPy array time: 0.0026628971099853516 seconds


In [12]:
# to compare in memory consumption by Python list and numpy array
import sys 
# for Python list
# print(f"Python list size: {sys.getsizeof(py_list) * len(py_list)} bytes") 
# the above line has flowed becuase it just multiplied the size of the outer boxgnores the actual weight of the data items

# here is the correct operation: To get the true size, you must weigh the container box plus every individual object it points to.
total_size = sys.getsizeof(py_list) + sum(sys.getsizeof(item) for item in py_list)
print(f"Python list size: {total_size} bytes")

# for Numpy array
print(f"Numpy array size: {np_array.nbytes} bytes")

Python list size: 36000056 bytes
Numpy array size: 8000000 bytes


In [22]:
# Create array from Lists 
# Create 1D array from 1D list
arr1D = np.array([1,2,3,4,5])
print(f"Array is: {arr1D}, Type: {type(arr1D)},  Data Type: {arr1D.dtype}, Shape: {arr1D.shape}")

# array is of one data type so here array will shift itself to string
array1D = np.array([1,2,3,4,5,"primAI"])
print(f"Array of string: {array1D} and Data Type is: {array1D.dtype}")

# now 2D array 
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"{arr2D}, Type is: {type(arr2D)} and shape is: {arr2D.shape}")

Array is: [1 2 3 4 5], Type: <class 'numpy.ndarray'>,  Data Type: int64, Shape: (5,)
Array of string: ['1' '2' '3' '4' '5' 'primAI'] and Data Type is: <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]], Type is: <class 'numpy.ndarray'> and shape is: (3, 3)


In [38]:
# creating array from scractch
# creaing 1D array
arr2_1D = np.ones((3,))
print(arr2_1D, arr2_1D.shape)

# creating 2D-array with 2-rows, and 4-columns and values prefill with zeros
arr3 = np.zeros((2,4), dtype= "int64")
print(arr3, arr3.shape)

# creating 2D-array with 4-rows and 3-columns and values prefill with ones
arr4 = np.ones((4,3), dtype= "U21")
print(arr4, arr4.shape, arr4.dtype)

# prefill with value use full function
arr5 = np.full((4,3), 100)
print(arr5, arr5.shape, arr5.dtype)

# create identity matrix using eye funciton
arr6 = np.eye(3)
print(arr6, arr6.shape, arr6.dtype)

# create arange funciton like arange(start, end, step)
arr7 = np.arange(0,14,2)
print(arr7, arr7.shape, arr7.dtype)

# creating evenly spaced arrays use of linspace(starting, ending , number of values in array)
arr8 = np.linspace(1,100, 5)
print(arr8, arr8.shape, arr8.dtype)

[1. 1. 1.] (3,)
[[0 0 0 0]
 [0 0 0 0]] (2, 4)
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']] (4, 3) <U21
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3) int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) float64
[ 0  2  4  6  8 10 12] (7,) int64
[  1.    25.75  50.5   75.25 100.  ] (5,) float64


In [40]:
# Properties of array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimensions = m x n
print(arr.size) # total elements 
print(arr.dtype) # data type
print(arr.ndim) # print total dimension

# type casting one is from scratch as we have done in 5th cell second operation and now here for existing one
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [43]:
# Other important operation of array
# 1. Reshaping of an array done only having compatible number of elements
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3,2))
print(reshaped_arr, reshaped_arr.shape)

# 2. form 2D array to 1D array
flattend_arr = arr.flatten() 
print(flattend_arr, flattend_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [55]:
# Indixing on an array 
# Indixing on 1D array
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

# Indixing on 2D array in this we specify the row and then column
arr = np.array([[1,2,3],[4,5,6]])
print("here is 2D array indixing")
print(arr[0][1])
print(arr[1][2])

# Fancy Indexing
arr = np.array([1,2,3,4,5])
ind = [0,2,4]
print(arr[ind])

# Boolean Indixing is done based on condition 
arr = np.array([1,2,3,4,5])
print(arr[arr > 3])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

# Fancy indixing applied to 2D array
arr = np.array([[1,2,3],[4,5,6]])
idx_row = [0,1]
idx_col = [1,2]
print(arr[idx_row, idx_col])

1
4
here is 2D array indixing
2
6
[1 3 5]
[4 5]
[2 4]
[1 3 5]
[2 6]


In [60]:
# Slicing in arrays
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # from index 1 to 3
print(arr[1:]) # from index 1 to end
print(arr[:4]) # from index 0 to 3
print(arr[:]) # entire array
print(arr[::2]) # entire array with one step left

# same operation for 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0:2, 0:2 ]) # from index 1 to 3
print(arr[1:, 1:2]) # from index 1 to end
print(arr[:2, 0:2 ]) # from index 0 to 3
print(arr[:, :]) # entire array
print(arr[::2, ::2]) # entire array with one step left

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[[1 2]
 [4 5]]
[[5]]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
[[1 3]]


In [67]:
# in slicing python list make copy while numpy array make view only that give difference of memory consumption
# copy vs view

# here we discussed python list 
# num = [1,2,3,4,5]
# sub_list = num[1:4]
# print(sub_list)
# print(num)

# sub_list [0] = 20
# print(sub_list)
# print(num)

#here we discussed Numpy arr how create view not copy
# arr = np.array([1,3,4,5,6])
# sub_arr = arr[1:3]
# print(sub_arr)

# sub_arr [1] = 200
# print(sub_arr)
# print(arr)

#here we discussed Numpy array if you want to make copy 
arr = np.array([1,3,4,5,6])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr [1] = 200
print(sub_arr)
print(arr)

[3 4]
[  3 200]
[1 3 4 5 6]


In [79]:
# Numpy Data types
# 1. intigers i.e. int8, int16, int32,int64, int128 
# important we do "downcasting" that we can make memory efficient like we have age max 200 or 300 so we can make suitable data type so that we can save memory that take extra 
# space not required for that or more than enough so we can make it efficient
arr = np.array([1,3,4,5,6])
print(arr, arr.dtype)

# 2. floating data type: float32, float64
arr = np.array([1,3,4,5,6,5.6])
print(arr, arr.dtype)

# 3. The boolean data type in NumPy stores binary values as either True or False
scores = np.array([45, 88, 92, 31, 75])
is_passing = scores >= 50
print("Boolean Array:", is_passing)
print("Data Type:", is_passing.dtype)
# 3. Use the boolean array to filter out the raw data
passed_scores = scores[is_passing]
print("Filtered Array:", passed_scores)

# 4. we have complex number like 2 + 3i here 2 is real part and 3i is imaginary part : like complex64, complex128
# important point if we have 64bsts number array will take 128 because complex numbers have two parts like 64 + 64 = 128
arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1.dtype)

# 5. string but we don't use string alot in numpy as we do numerical calculation: i.e. S(bute-str) & U(unicode-str)
arr = np.array([1,3,4,5,6, "helo"])
print(arr, arr.dtype)

# 6. Objects also same like string we don't use objects a lot 
arr = np.array(["prime", {1,2,3},3.14])
print(arr, arr.dtype)

[1 3 4 5 6] int64
[1.  3.  4.  5.  6.  5.6] float64
Boolean Array: [False  True  True False  True]
Data Type: bool
Filtered Array: [88 92 75]
[5.+8.j]
[1.+2.j]
complex128
['1' '3' '4' '5' '6' 'helo'] <U21
['prime' {1, 2, 3} 3.14] object


In [80]:
# Multi-dimensional arrays
# here we used 2D array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [86]:
# 3D arrays
arr3D = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]]) # 2 x 3 x 2
print(arr3D, arr3D.shape)

# Indexing
print(arr3D[0,1,1])
print(arr3D[1,2,0])

# slicing
print(arr3D[:, : , 0])

# also can replace value
arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
11
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [88]:
# Vectorization: here we don't loop through every element but we can access all at once provided by numpy on other hand in python list we do looping through every element
arr = np.array([1,3,4])
arr1 = np.array([5,6,7])
print(arr**2)
print(arr +10)
print(arr + arr1)

[ 1  9 16]
[11 13 14]
[ 6  9 11]


In [90]:
# Brodcasting: scalling our arrays without using extra memory
# to apply on two arrays it is only applicable when both arrays are equla(i.e. (2x3) and (2x3)) or one of them is 1(i.e. (2x3) and (1x3) or only 1)
arr1 = np.array([1,3,4]) #  shpae is: (3,) and we can say that it (1 x 3)
arr2 = np.array([[1,2,3],[4,5,6]]) # 2x3
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2) 

(3,)
(2, 3)
[[ 2  5  7]
 [ 5  8 10]]


In [91]:
# Vector Normalization: Normalization an array means transforming its values so they fit into a specific scale or range
# normalize 
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [95]:
# Important methematical functions 

# 1. Aggregation: in this we get some single output
arr = np.array([1,2,3,4,5])
print(np.sum(arr)) # sum ()
print(np.prod(arr)) # prod() called product
print(np.min(arr)) # min() gives minimum value
print(np.max(arr)) # max() gives maximum value
print(np.argmin(arr)) # argmin() gives index of minimum value
print(np.argmax(arr)) # argmax() gives index of maximum value
print(np.mean(arr)) # mean() gives mean
print(np.std(arr)) # std() gives standared deviation value x=[1,2,3,4] and formulas is variance = under-root(sumation( x1 - mean)square / N) so here x1 is like index 0,1,2,3... for all values separately
print(np.median(arr)) #median() gives midle valud of sorted arrays
print(np.var(arr)) # var() gives the value like we have x=[1,2,3,4] and formulas is variance = sumation( x1 - mean)square / N . 

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [98]:
# power function : calculate power of something
arr = np.array([1,2,3,4,5])
print(np.square(arr)) # calculate square of values
print(np.sqrt(arr)) # calculate square root for values
print(np.pow(arr, 3)) # calculate power to the value for each values


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [100]:
# Log and exponential  related fucntion
arr = np.array([1,2,3,4,5])
print(np.log(arr)) # calculate natural log for each values natural log is basically base to e (exponential)
print(np.log10(arr)) # calculate log values like log10 , log2
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [112]:
# function for rounding values
print(np.round(3.14))
print(np.round(3.54))
print(np.ceil(3.14)) # to round up 
print(np.floor(3.14)) # to round down
print(np.trunc(3.14)) # to remove the last 

arr = np.array([1,3,4,2,-3,4,-5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) # abs function is basically for absolute value 

3.0
4.0
4.0
3.0
3.0
[-5 -3  1  2  3  4]
[-5 -3  1  2  3  4  4]
[1 3 4 2 3 4 5]


[2 3 4 5]
[1 3 5]
[6 5 4 3 2 1]
