In [16]:
import numpy as np
# Q-1 
#list of temperatures recorded over 7 days:
temps = [28, 31, 29, 35, 30, 33, 27]

# 1.Convert the list into a NumPy array
arr = np.array(temps)

# 2. Print:shape, size, ndim, dtype
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

# 3.Find: maximum temperature, minimum temperature, average temperature
print(arr.max())
print(arr.min())
print(arr.mean())

# 4. Print all temperatures greater than 30.
print(arr[arr >30])

# 5. Print temperatures at indices [0, 3, 6].
# fancy indexing
idx = [0,3,6]
print(arr[idx])

# 6. Print every second temperature using slicing.
print(arr[::2])

(7,)
7
1
int64
8
35
27
30.428571428571427
[31 35 33]
[28 35 27]
[28 29 30 27]


In [41]:
# Q -2 Reshape + Multi-dimensional Arrays + Axis Operations
numbers = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

# 1. Convert it into a 3 x 4 matrix.
reshaped = numbers.reshape((3,4))
print(reshaped)

# 2. Print: shape, ndim, size of the new matrix.
print(reshaped.shape)
print(reshaped.ndim)
print(reshaped.size)

# 3 Print: first row, second column, last row, element 80
print(reshaped[0])
print(reshaped[: , 1])
print(reshaped[: , -1])
print(reshaped[1, -1])

# 4. Calculate: total sum, row-wise sum, column-wise sum
print(reshaped.sum())
print(reshaped.sum(axis = 1))
print(reshaped.sum(axis = 0))

# 5 Calculate: row-wise mean, column-wise mean
print(reshaped.mean(axis = 1))
print(reshaped.mean(axis = 0))

# 6. [[20 30][60 70][100 110]]
print(reshaped[:, 1:3]) 

# 7. Replace the entire first row with 999 using NumPy indexing only.
reshaped[0] = 999
print(reshaped)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
2
12
[10 20 30 40]
[ 20  60 100]
[ 40  80 120]
80
780
[100 260 420]
[150 180 210 240]
[ 25.  65. 105.]
[50. 60. 70. 80.]
[[ 20  30]
 [ 60  70]
 [100 110]]
[[999 999 999 999]
 [ 50  60  70  80]
 [ 90 100 110 120]]
